const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
const testModule = { exports: {} };
new Function('module', fs.readFileSync(path.join(__dirname, '../lenremont-page-importer/assets/seo-import.js'), 'utf8'))(testModule);
const seo = testModule.exports;
const inputs = {};
const doc = { location: { href: 'https://www.lenremont.ru/wp-admin/post.php' }, getElementById: id => inputs[id], defaultView: { Event: class { constructor(type) { this.type = type; } } } };
for (const id of Object.values(seo.fields)) inputs[id] = { value: '', isConnected: true, ownerDocument: doc, closest: () => ({}), events: [], dispatchEvent(e) { this.events.push(e.type); } };
assert.deepEqual(seo.normalize(undefined), {});
assert.deepEqual(seo.normalize({ title: '', canonical: ' ' }), {});
assert.throws(() => seo.normalize([]));
assert.throws(() => seo.normalize({ title: {} }));
assert.throws(() => seo.normalize({ canonical: 'javascript:alert(1)' }, doc.location.href));
assert.throws(() => seo.normalize({ canonical: '//evil.test' }, doc.location.href));
assert.throws(() => seo.normalize({ ogImageId: -1 }));
assert.equal(seo.normalize({ canonical: '/test/' }, doc.location.href).canonical, 'https://www.lenremont.ru/test/');
const title = inputs[seo.fields.title];
title.value = 'Manual title';
let plan = seo.plan({ title: 'Replacement', description: 'New description', robots: 'index' }, doc, false);
assert.equal(plan.changes.length, 1);
assert.equal(plan.preserved.length, 1);
const applied = seo.apply(plan);
assert.equal(title.value, 'Manual title');
assert.deepEqual(inputs[seo.fields.description].events, ['input', 'change']);
assert.equal(seo.undo(applied), 1);
plan = seo.plan({ title: '<b>Replacement</b>' }, doc, true);
seo.apply(plan);
assert.equal(title.value, 'Replacement');
title.value = 'Later manual edit';
assert.equal(seo.undo(plan.changes), 0, 'undo preserves later manual edits');
plan = seo.plan({ title: 'Stale', description: 'Do not partially apply' }, doc, true);
title.value = 'Concurrent edit';
assert.throws(() => seo.apply(plan));
assert.equal(inputs[seo.fields.description].value, '');
delete inputs[seo.fields.canonical];
assert.deepEqual(seo.plan({ canonical: '/test/' }, doc, false).missing, ['canonical']);
const catalog = JSON.parse(fs.readFileSync(path.join(__dirname, '../lenremont-page-importer/examples/catalog.json')));
for (const name of catalog.map(page => page.example.replace(/\.json$/, ''))) {
  const m = JSON.parse(fs.readFileSync(path.join(__dirname, '../lenremont-page-importer/examples', name + '.json')));
  assert.equal(Object.keys(seo.normalize(m.seo, doc.location.href)).length, 5);
  assert.ok(!m.seo.canonical && !m.seo.robots, 'no accidental canonical or indexing changes');
}
console.log('SEO tests passed: mappings, validation, preserve, overwrite, undo, stale preview, missing fields, all manifests.');
