import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
const cli=fileURLToPath(new URL('./lr-wp.mjs',import.meta.url));
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'lr-skill-tool-'));
function run(args,status=0){
  const result=spawnSync(process.execPath,[cli,...args],{cwd:temporary,encoding:'utf8',windowsHide:true});
  assert.equal(result.status,status,result.error?.message||result.stderr);
  return result.stdout;
}
const info=JSON.parse(run(['info']));
assert.equal(info.version,'0.13.0');
assert.equal(info.wordpressWrites,false);
const manifest=path.join(temporary,'page.json');
run(['create-json','--out',manifest,'--title','Example','--slug','service-example']);
const before=fs.readFileSync(manifest,'utf8');
run(['create-json','--out',manifest,'--title','Replacement','--slug','replacement'],1);
assert.equal(fs.readFileSync(manifest,'utf8'),before);
assert.equal(JSON.parse(run(['validate','--manifest',manifest])).structure,'PASS');
const broken=JSON.parse(before);
broken.sections[2].anchor='details';
const invalid=path.join(temporary,'invalid.json');
fs.writeFileSync(invalid,JSON.stringify(broken));
run(['validate','--manifest',invalid],1);
run(['create-json','--out',path.join(temporary,'escape.json'),'--title','Example','--slug','../escape'],1);
assert.equal(fs.existsSync(path.join(temporary,'escape.json')),false);
const work=path.join(temporary,'workbench');
run(['init','--out',work]);
const marker=path.join(work,'user-owned.txt');
fs.writeFileSync(marker,'keep');
run(['init','--out',work],1);
assert.equal(fs.readFileSync(marker,'utf8'),'keep');
assert.ok(fs.existsSync(path.join(work,'wordpress-plugin/lenremont-page-importer/assets/reference/original.css')));
assert.equal(fs.existsSync(path.join(work,'node_modules')),false);
console.log('PASS tool portability, JSON generation/validation, duplicate IDs, bad slug, non-overwrite guards.');
console.log('Temporary verification artifacts: '+temporary);
