<?php
/** Uses the native block helpers from design-system.php. */
if (! defined('ABSPATH')) exit;
$variants = array();
$add = static function ($slug, $title, $description, $content) use (&$variants): void {
	$variants['ai-' . $slug] = array('title' => 'Ленремонт · ' . $title, 'description' => $description, 'categories' => array('lr-ai-sections'), 'viewportWidth' => 1280, 'content' => $content, 'keywords' => array('Ленремонт', $title));
};
$plain = static function ($title, $text) use ($group, $h, $p) { return $group('lr-ai-stack lr-ai-plain-item', $h($title, 3) . $p($text), '', $title); };
$quiz = static function ($variant = 'list') { return get_comment_delimited_block_content('lenremont/service-quiz', array('variant' => $variant), ''); };
$intro = $h('Поможем разобраться с вашей задачей', 1) . $p('Коротко опишите услугу, для кого она подходит и какой результат получает клиент.', 'lr-ai-lead') . $buttons($button('Обсудить задачу', '#lr-ai-contact'));
$add('hero-light', 'Первый экран / светлый', 'Спокойный светлый Hero: текст слева, фотография справа.', $section('', $group('lr-ai-grid lr-ai-grid--two lr-ai-hero-grid', $group('lr-ai-stack', $intro) . $image)));
$add('hero-centered', 'Первый экран / по центру', 'Без фотографии: центрированный заголовок и одно основное действие.', $section('', $group('lr-ai-centered lr-ai-stack', $intro), 'soft'));
$add('hero-quiz', 'Первый экран / с квизом', 'Описание услуги и квиз в двух колонках. Вопросы настраиваются в боковой панели блока.', $section('', $group('lr-ai-grid lr-ai-grid--two lr-ai-hero-grid', $group('lr-ai-stack', $h('Начнём с вашей задачи', 1) . $p('Ответьте на несколько вопросов — это поможет обсудить нужную услугу.', 'lr-ai-lead')) . $quiz()), 'soft'));
$add('quiz', 'Квиз / отдельная секция', 'Пошаговый опрос, возврат, сброс и заявка через обработчик сайта. Настройки без JSON.', $section('', $group('lr-ai-quiz-narrow', $quiz()), '', 'lr-ai-quiz', 'Квиз'));
$add('quiz-aside', 'Квиз / с пояснением', 'Поясняющий текст слева, ответы в две колонки справа.', $section('Подберём следующий шаг', $group('lr-ai-grid lr-ai-grid--two', $group('lr-ai-stack', $p('Расскажите о задаче. Ответы помогут специалисту подготовиться к разговору.') . $p('Точная стоимость и условия согласуются отдельно.', 'lr-ai-muted')) . $quiz('cards')), 'soft', 'lr-ai-quiz'));
$add('advantages-plain', 'Преимущества / без карточек', 'Три колонки с тонкой верхней линией: минимум рамок и фонов.', $section('Что важно в нашей работе', $group('lr-ai-grid', $plain('Понятные условия', 'Укажите, как согласуются работы и стоимость.') . $plain('Внимание к задаче', 'Опишите, какие детали вы уточняете перед началом.') . $plain('Проверка результата', 'Расскажите, как клиент принимает работу.'))));
$rows = '';
foreach (array('Основная услуга', 'Дополнительные работы', 'Консультация') as $title) {
	$rows .= $group('lr-ai-row lr-ai-grid lr-ai-grid--two', $group('lr-ai-stack', $h($title, 3) . $p('Добавьте состав работ и условия.')) . $buttons($button('Уточнить подробности', '#lr-ai-contact', 'outline')));
}
$add('services-list', 'Услуги / список', 'Строки вместо карточек. Удобно для короткого каталога услуг.', $section('Выберите услугу', $rows));
$photoCards = '';
foreach (array('Направление 1', 'Направление 2') as $title) $photoCards .= $group('lr-ai-stack', $image . $h($title, 3) . $p('Кому подходит и что входит в услугу.') . $buttons($button('Узнать подробнее', '#lr-ai-contact', 'outline')));
$add('services-photo', 'Услуги / с фотографиями', 'Два направления с большими изображениями, описаниями и ссылками.', $section('Направления работы', $group('lr-ai-grid lr-ai-grid--two', $photoCards), 'soft'));
$priceRows = '';
foreach (array('Работа 1', 'Работа 2', 'Работа 3') as $title) $priceRows .= $group('lr-ai-row lr-ai-grid lr-ai-grid--two', $group('lr-ai-stack', $h($title, 3) . $p('Опишите, что входит в стоимость.', 'lr-ai-muted')) . $p('Укажите цену', 'lr-ai-price'));
$add('prices-rows', 'Цены / строки', 'Компактный прайс без тяжёлых карточек. Каждая строка редактируется отдельно.', $section('Стоимость услуг', $priceRows . $p('Добавьте условия расчёта и дату актуальности цен.', 'lr-ai-small lr-ai-muted')));
$add('prices-compare', 'Цены / два варианта', 'Два сопоставимых предложения: состав, ограничения и стоимость.', $section('Варианты работ', $group('lr-ai-grid lr-ai-grid--two', $card('Базовый объём', 'Перечислите конкретные работы.', $p('Укажите цену', 'lr-ai-price') . $p('Уточните, что не входит в стоимость.', 'lr-ai-small lr-ai-muted')) . $card('Расширенный объём', 'Укажите отличия от базового объёма.', $p('Укажите цену', 'lr-ai-price') . $p('Укажите условия выбора этого варианта.', 'lr-ai-small lr-ai-muted'))), 'soft'));
$timeline = '';
foreach (array('Обращение' => 'Опишите способ передачи задачи.', 'Согласование' => 'Объясните, как согласуются стоимость и срок.', 'Выполнение' => 'Расскажите о ходе работы.', 'Приёмка' => 'Опишите проверку результата.') as $title => $text) $timeline .= $group('lr-ai-row lr-ai-grid lr-ai-grid--two', $h($title, 3) . $p($text));
$add('process-vertical', 'Этапы / вертикальный список', 'Последовательность сверху вниз, без отдельных карточек.', $section('Как проходит работа', $timeline, '', 'lr-ai-process'));
$add('faq-split', 'Вопросы / две колонки', 'Слева пояснение, справа раскрывающиеся ответы.', $section('Ответы на вопросы', $group('lr-ai-grid lr-ai-grid--two', $group('lr-ai-stack', $p('Соберите здесь вопросы, которые клиенты задают перед обращением.') . $buttons($button('Задать свой вопрос', '#lr-ai-contact', 'outline'))) . $group('lr-ai-stack', $faq))));
$add('review-featured', 'Отзывы / один подробный', 'Один подлинный отзыв с источником, без оценок-заглушек.', $section('Опыт клиента', $group('lr-ai-prose lr-ai-stack', $quote), 'soft'));
$add('gallery-featured', 'Галерея / один кейс', 'Большая фотография и описание задачи, решения и результата.', $section('Пример выполненной работы', $group('lr-ai-grid lr-ai-grid--two lr-ai-hero-grid', $image . $group('lr-ai-stack', $h('Название проекта', 3) . $p('Задача клиента: добавьте описание.') . $p('Что сделали: укажите реальные работы.') . $p('Результат: расскажите о проверяемых изменениях.')))));
$add('contact-columns', 'Контакты / две колонки', 'Контактные данные отдельно от правил приёма. Заполните адрес и график.', $section('Как связаться с нами', $group('lr-ai-grid lr-ai-grid--two', $group('lr-ai-stack', $h('Обсудить задачу', 3) . $p('Уточните детали по телефону.') . $buttons($button('+7 (812) 344-44-44', 'tel:+78123444444'))) . $group('lr-ai-stack', $h('Адрес и часы работы', 3) . $p('Укажите действующий адрес приёма.') . $p('Добавьте актуальный график и условия визита.'))), 'soft', 'lr-ai-contact'));
$add('cta-inline', 'Призыв / компактная строка', 'Короткий текст и кнопка рядом; на телефоне — друг под другом.', $section('', $group('lr-ai-grid lr-ai-grid--two lr-ai-hero-grid', $group('lr-ai-stack', $h('Обсудим вашу задачу?') . $p('Расскажите, какой результат вам нужен.')) . $buttons($button('Связаться с нами', '#lr-ai-contact'))), 'soft lr-ai-compact'));
$add('materials', 'Материалы / сравнение', 'Две колонки для описания материалов и ограничений их применения.', $section('Материалы и варианты', $group('lr-ai-grid lr-ai-grid--two', $plain('Материал 1', 'Назовите материал, его свойства и ограничения. Подтвердите характеристики перед публикацией.') . $plain('Материал 2', 'Покажите отличия и объясните, для каких задач подходит материал.'))));
$add('team', 'Команда / специалисты', 'Две фотографии и краткие сведения. Не публикуйте неподтверждённые квалификации.', $section('Кто работает с вашей задачей', $group('lr-ai-grid lr-ai-grid--two', $group('lr-ai-stack', $image . $h('Имя специалиста', 3) . $p('Роль и подтверждённая специализация.')) . $group('lr-ai-stack', $image . $h('Имя специалиста', 3) . $p('Роль и подтверждённая специализация.')))));
$add('conditions', 'Условия / важная информация', 'Гарантия, ограничения и порядок согласования в двух колонках.', $section('Условия выполнения работ', $group('lr-ai-grid lr-ai-grid--two', $plain('Перед началом', 'Укажите, какие сведения или документы понадобятся и что согласуется заранее.') . $plain('После выполнения', 'Укажите фактические условия гарантии, ограничения и порядок обращения.')), 'soft'));
$variants['ai-page-quiz'] = array('title' => 'Ленремонт · Страница услуги с квизом', 'description' => 'Светлая сборка: Hero с квизом, преимущества, услуги, цены, этапы, FAQ и контакты. Все тексты-примеры замените перед публикацией.', 'categories' => array('lr-ai-pages'), 'viewportWidth' => 1280, 'content' => $group('lr-ai-page', implode("\n", array_map(static function ($key) use ($variants) { return $variants['ai-' . $key]['content']; }, array('hero-quiz', 'advantages-plain', 'services-list', 'prices-rows', 'process-vertical', 'faq-split', 'contact-columns'))), 'hop-gutenberg', 'Страница Ленремонт'));
return $variants;
